sonar.projectKey=fanvault-frontend
sonar.projectName=FanVault Frontend
sonar.organization=fanvault-cloudops
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/coverage/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
