replicaCount: 2

image:
  pullPolicy: IfNotPresent
  repository: 773384830607.dkr.ecr.us-east-1.amazonaws.com/fanvault-prod-ai-service
  tag: v0.0.1

hpa:
  minReplicas: 2
  maxReplicas: 5

config:
  ENVIRONMENT: "production"
  S3_PRODUCT_IMAGES_BUCKET: "fanvault-dev-product-images-773384830607"

serviceAccount:
  name: ai-service
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::773384830607:role/fanvault-ai-irsa-role"
