replicaCount: 2

image:
  pullPolicy: IfNotPresent
  repository: 773384830607.dkr.ecr.us-east-1.amazonaws.com/fanvault-prod-user-service
  tag: v0.0.1

hpa:
  minReplicas: 2
  maxReplicas: 5

config:
  NODE_ENV: "production"
  USE_SECRETS_MANAGER: "true"
  SECRET_ID: "fanvault-prod-app-secrets"
  COGNITO_REGION: "us-east-1"
  COGNITO_USER_POOL_ID: "us-east-1_O7cQQXD1P"
  COGNITO_CLIENT_ID: "3fioa78u18rkf7c3kiqb3sud55"
  DYNAMODB_TABLE_PROFILES: "fanvault-dev-profiles"

serviceAccount:
  name: user-service
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::773384830607:role/fanvault-user-irsa-role"
