sonar.projectKey=fanvault-ai-service
sonar.projectName=FanVault AI Service
sonar.organization=fanvault-cloudops
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/tests/**
sonar.python.version=3.12
