apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "frontend.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "frontend.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "frontend.fullname" . }}
